/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.app1;

import org.junit.Test;

public class AppTest {
  @Test public void appHasAGreeting() {
    //    App classUnderTest = new App();
    //    //        assertNsotNull("app should shave a greeting", classUnderTest.getGreeting());
  }
}
